### ISSUE TITLE
Only run deploy hook on master branch

### ISSUE THREAD

**Issue by felixdulfer** [make-ci-great-again/docker-laravel-webpack-ci#3]
Travis deploy hook to Docker Hub fires on merge requests, which would build the master branch, even if the tests on Travis are being ran on a different branch. 

The deploy hook should only trigger on master branch.

Current config:

```yaml
jobs:
  include:
    - stage: deploy
      script:
        - docker images
        - curl -X POST $DOCKER_HUB_TRIGGER_URL
```

Proposed config (?):

```yaml
jobs:
  include:
    - stage: deploy
      branches:
        only:
          - master
      script:
        - docker images
        - curl -X POST $DOCKER_HUB_TRIGGER_URL
```
